;(function(Drupal,$,firebase,drupalSettings,window){if(window.NodeList&&!NodeList.prototype.forEach){NodeList.prototype.forEach=function(callback,thisArg){thisArg=thisArg||window;for(var i=0;i<this.length;i++){callback.call(thisArg,this[i],i,this);}};}
var Bookmark;Bookmark={db:null,storage:window.localStorage,env:drupalSettings.lt_firebase.environment,uid:drupalSettings.user.uid,favourites:JSON.parse(window.localStorage.getItem("favourites"))||{},no_favourites:"<div class=\"no-bookmark\">"+(drupalSettings.lt_bookmark?drupalSettings.lt_bookmark.noFavoriteContent:'')+"</div>",showFavourites:function(placeholder){var template=document.getElementById('favorite-article-template').innerHTML,html=[],articles=[];Mustache.parse(template);var self=this;this.db.collection(self.env+"/"+self.uid+"/favourites").get().then(querySnapshot=>{let ids=[];querySnapshot.forEach(function(doc){self.favourites[doc.id]=true;ids.push(+doc.id);});articles=(async(ids)=>{const query='{\n'+
'  contentsByIds(ids: '+JSON.stringify(ids)+') {\n'+
'    ... on ContentInterface {\n'+
'      id,\n'+
'      title,\n'+
'      kicker,\n'+
'      datePublication,\n'+
'      lead,\n'+
'      link,\n'+
'      image {\n'+
'        derivative(style: MEDIUM) {\n'+
'          url\n'+
'        }\n'+
'      }\n'+
'    }\n'+
'  }\n'+
'}';const data=await fetch(Drupal.url('app/graphql'),{method:"POST",headers:{'Content-Type':'application/json','Accept':'application/json',},body:JSON.stringify({query:query})}).then(response=>{return response.json()});return data.data.contentsByIds;})(ids);self.storage.setItem("favourites",JSON.stringify(self.favourites));return articles;}).then(articles=>{articles.forEach(article=>{html.push(Mustache.render(template,article));});return html;}).then(html=>{if(html.length>0){placeholder.innerHTML=html.join('');window.dataLayer.push({'event':'Bookmark','eventCategory':'Bookmark','eventAction':'Shown','eventLabel':'With Favourites'});const links=placeholder.querySelectorAll('.delete-bookmark-action');links.forEach(function(el){el.addEventListener('click',function(event){const articleId=this.dataset.articleId;Bookmark.deleteFavourite({id:articleId});const block=document.getElementById('bookmark-'+articleId);block.classList.add('has-faded');setTimeout(function(){block.classList.add('has-collapsed');setTimeout(function(){block.remove();},350);},350);const links=placeholder.querySelectorAll('.delete-bookmark-action');if(links.length===0){placeholder.innerHTML=self.no_favourites;}
event.preventDefault();});});}else{placeholder.innerHTML=self.no_favourites;window.dataLayer.push({'event':'Bookmark','eventCategory':'Bookmark','eventAction':'Show','eventLabel':'Without Favourites'});}});},syncFavourites:function(){var self=this;this.db.collection(self.env+"/"+self.uid+"/favourites").get().then(function(querySnapshot){querySnapshot.forEach(function(doc){self.favourites[doc.id]=true;});self.storage.setItem("favourites",JSON.stringify(self.favourites));window.dataLayer.push({'event':'Bookmark','eventCategory':'Bookmark','eventAction':'Synced'});});},addToFavourite:function(article){var self=this;article.saveDate=Date.now()/1000;this.db.collection(self.env+"/"+self.uid+"/favourites").doc(article.id).set(article).then(function(doc){self.favourites[article.id]=true;self.storage.setItem("favourites",JSON.stringify(self.favourites||{}));window.dataLayer.push({'event':'Bookmark','eventCategory':'Bookmark','eventAction':'Added'});}).catch(function(error){console.log("Error : "+error);});},deleteFavourite:function(article){var self=this;this.db.collection(self.env+"/"+self.uid+"/favourites").doc(article.id).delete().then(function(){delete self.favourites[article.id];self.storage.setItem("favourites",JSON.stringify(self.favourites||{}));window.dataLayer.push({'event':'Bookmark','eventCategory':'Bookmark','eventAction':'Deleted'});}).catch(function(error){console.log("Oops error : "+error);});},_updateDOM:function(){var matches=document.querySelectorAll('.bookmark-action-add');if(matches.length>0){var self=this;matches.forEach(function(elem){if(self.favourites){var articleId=elem.dataset.articleId;if(self.favourites[articleId]){elem.classList.add('is-bookmarked');}}
if(elem.dataset.bookmarkOnce){return;}
elem.setAttribute('data-bookmark-once','true');elem.querySelector('a').addEventListener('click',function(event){if(!this.dataset.favourite){return;}
var parent=this.parentNode,article=JSON.parse(this.dataset.favourite);if(parent.classList.contains("is-bookmarked")){Bookmark.deleteFavourite(article);parent.classList.remove("is-bookmarked");}else{Bookmark.addToFavourite(article);parent.classList.add("is-bookmarked");}});});}},_initObserver:function(){const self=this;const observer=new window.MutationObserver(function(mutations){for(let mutation of mutations){if(mutation.addedNodes&&mutation.addedNodes.length>0){for(let node of mutation.addedNodes){if(node.nodeType===Node.ELEMENT_NODE){let hasFollowButton=node.classList.contains('bookmark-action-add')||node.querySelectorAll('.bookmark-action-add').length;if(hasFollowButton){self._updateDOM();return;}}}}}});observer.observe(document.body||document.documentElement,{childList:true,subtree:true});},init:function(){this._updateDOM();this._initObserver();if(firebase&&firebase.apps.length>0&&this.db===null){firebase.firestore().settings({experimentalForceLongPolling:true});this.db=firebase.firestore();firebase.auth().onAuthStateChanged(function(user){if(user){if(document.getElementById('my-favorites-articles')){let elem=document.getElementById('my-favorites-articles');Bookmark.showFavourites(elem);}}});}
if(this.uid){var last_sync=window.sessionStorage.getItem('favourites_sync');if(last_sync===null||(Date.now()-last_sync>7.2e+6)){this.syncFavourites();window.sessionStorage.setItem("favourites_sync",Date.now());}}else{if(this.favourites.length>0||this.storage.getItem("favourites")){this.favourites=null;this.storage.removeItem("favourites");window.sessionStorage.removeItem("favourites_sync");}}}};Bookmark.init();})(Drupal,jQuery,window.firebase||null,drupalSettings,window);